title: "Daniel Youn"
author: "Daniel Youn"
description: "Daniel Youn — Systems Administrator portfolio. IT projects, networking labs, and certifications."
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false
show_frame: true
show_sidebar: false
show_minimal: false

# Menu (icons: https://fontawesome.com/v5/icons/)
navigation:
  - {file: "README.md", title: "README"}
  - {file: "resume.pdf", title: "Resume"}

external:
  - {title: Mail, icon: envelope, url: "mailto:danielyoun247@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/FirstNPC"}
  - {title: LinkedIn, icon: linkedin-in, url: "https://www.linkedin.com/in/djyoun/"}

comments:
  # disqus_shortname: ""
  # isso_domain: ""

plugins:
  - jekyll-feed
